# Generated by Django 3.2.8 on 2021-11-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'product_category', 'verbose_name_plural': 'product categories'},
        ),
    ]
